#!/usr/bin/env bash

# Copyright (c) 2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script generates a docker-compose override file for multi-GPU worker deployments.
# Each worker is assigned to a specific GPU device.

set -euo pipefail

NUM_WORKERS=${NUM_WORKERS:-1}
VARIANT_TYPE=${VARIANT_TYPE:-gpu}
OUTPUT_FILE=${1:-../docker/docker-compose.workers.yml}

if (( NUM_WORKERS <= 1 )); then
  # Remove the override file if it exists and we only need 1 worker
  rm -f "${OUTPUT_FILE}"
  exit 0
fi

if [[ "${VARIANT_TYPE}" != "gpu" ]]; then
  echo "Multi-worker support is currently only implemented for GPU variant"
  exit 1
fi

cat > "${OUTPUT_FILE}" << 'HEADER'
# Auto-generated file for multi-GPU worker deployment
# DO NOT EDIT - This file is regenerated by generate_multi_worker_compose.sh

services:
HEADER

for i in $(seq 0 $((NUM_WORKERS - 1))); do
  cat >> "${OUTPUT_FILE}" << EOF
  presto-native-worker-gpu-${i}:
    extends:
      file: docker-compose.common.yml
      service: presto-base-native-worker
    container_name: presto-native-worker-gpu-${i}
    image: presto-native-worker-gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=${i}
      - PROFILE=\${PROFILE}
      - PROFILE_ARGS=\${PROFILE_ARGS}
    depends_on:
      - presto-coordinator
    volumes:
      - ./config/generated/gpu/etc_common:/opt/presto-server/etc
      - ./config/generated/gpu/etc_worker/node_worker${i}.properties:/opt/presto-server/etc/node.properties
      - ./config/generated/gpu/etc_worker/config_native.properties:/opt/presto-server/etc/config.properties
      - ./config/generated/gpu/etc_worker/catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties

EOF
done

echo "Generated ${OUTPUT_FILE} with ${NUM_WORKERS} GPU workers"
